package com.mycompany.sudoku;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import com.mycompany.sudoku.PuzzlesAndSolutions;
import com.mycompany.sudoku.Sudoku;
import java.awt.image.BufferedImage;
import java.awt.Image;
import javax.swing.*;
import java.io.File;
import javax.imageio.ImageIO;
import java.awt.*;

/**
 *
 * @author noah
 */
public class DifficultyChooserGUI extends javax.swing.JFrame {

    private int count = 0;
    private ImageIcon[] puzzlesEasy = new ImageIcon[8];
    private ImageIcon[] puzzlesInter = new ImageIcon[8];
    private ImageIcon[] puzzlesHard = new ImageIcon[8];
    private ImageIcon[] puzzlesExpert = new ImageIcon[8];
    private ImageIcon[] currentPuzzles;

    private String pathEasy = "puzzles_images/easy/";
    private String pathInter = "puzzles_images/Intermediate/";
    private String pathHard = "puzzles_images/hard/";
    private String pathExpert = "puzzles_images/expert/";

    private PuzzlesAndSolutions puzzlesAndSolutions = new PuzzlesAndSolutions();

    private String[] endPath = {"puzzle1", "puzzle2", "puzzle3", "puzzle4", "puzzle5", "puzzle6", "puzzle7", "puzzle8",};

    /**
     * Creates new form DificultyChooserGUI
     */
    public DifficultyChooserGUI() {
        initComponents();

        setImages(puzzlesEasy, pathEasy);
        setImages(puzzlesInter, pathInter);
        setImages(puzzlesHard, pathHard);
        setImages(puzzlesExpert, pathExpert);

        BtnNext.setVisible(false);
        BtnPrev.setVisible(false);
        BtnPuzzleSelect.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BtnEasy = new javax.swing.JButton();
        BtnExpert = new javax.swing.JButton();
        BtnHard = new javax.swing.JButton();
        BtnInter = new javax.swing.JButton();
        BtnNext = new javax.swing.JButton();
        BtnPrev = new javax.swing.JButton();
        LabelPuzzleImages = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        LabelNum = new javax.swing.JLabel();
        LabelDifficulity = new javax.swing.JLabel();
        BtnPuzzleSelect = new javax.swing.JButton();
        BtnExit = new javax.swing.JButton();

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        jButton4.setText("jButton4");

        jButton5.setBackground(new java.awt.Color(0, 51, 204));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Select");

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(0, 0, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Choose your difficulty!");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setBackground(new java.awt.Color(0, 0, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Easy");

        jLabel3.setBackground(new java.awt.Color(0, 0, 204));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Intermediate");

        jLabel4.setBackground(new java.awt.Color(0, 0, 204));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Hard");

        jLabel5.setBackground(new java.awt.Color(0, 0, 204));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Expert");

        BtnEasy.setBackground(new java.awt.Color(0, 51, 204));
        BtnEasy.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnEasy.setForeground(new java.awt.Color(255, 255, 255));
        BtnEasy.setText("Select");
        BtnEasy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEasyActionPerformed(evt);
            }
        });

        BtnExpert.setBackground(new java.awt.Color(0, 51, 204));
        BtnExpert.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnExpert.setForeground(new java.awt.Color(255, 255, 255));
        BtnExpert.setText("Select");
        BtnExpert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExpertActionPerformed(evt);
            }
        });

        BtnHard.setBackground(new java.awt.Color(0, 51, 204));
        BtnHard.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnHard.setForeground(new java.awt.Color(255, 255, 255));
        BtnHard.setText("Select");
        BtnHard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHardActionPerformed(evt);
            }
        });

        BtnInter.setBackground(new java.awt.Color(0, 51, 204));
        BtnInter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnInter.setForeground(new java.awt.Color(255, 255, 255));
        BtnInter.setText("Select");
        BtnInter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInterActionPerformed(evt);
            }
        });

        BtnNext.setBackground(new java.awt.Color(0, 51, 204));
        BtnNext.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnNext.setForeground(new java.awt.Color(255, 255, 255));
        BtnNext.setText("Next");
        BtnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNextActionPerformed(evt);
            }
        });

        BtnPrev.setBackground(new java.awt.Color(0, 51, 204));
        BtnPrev.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnPrev.setForeground(new java.awt.Color(255, 255, 255));
        BtnPrev.setText("Previous");
        BtnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrevActionPerformed(evt);
            }
        });

        LabelPuzzleImages.setPreferredSize(new java.awt.Dimension(300, 300));

        LabelNum.setFont(new java.awt.Font("Noto Sans", 1, 20)); // NOI18N
        LabelNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelNum.setPreferredSize(new java.awt.Dimension(40, 20));

        LabelDifficulity.setFont(new java.awt.Font("Noto Sans", 1, 20)); // NOI18N
        LabelDifficulity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelDifficulity.setPreferredSize(new java.awt.Dimension(40, 30));

        BtnPuzzleSelect.setFont(new java.awt.Font("Noto Sans", 0, 8)); // NOI18N
        BtnPuzzleSelect.setText("Select Puzzle");
        BtnPuzzleSelect.setPreferredSize(new java.awt.Dimension(90, 30));
        BtnPuzzleSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPuzzleSelectActionPerformed(evt);
            }
        });

        BtnExit.setBackground(new java.awt.Color(70, 80, 82));
        BtnExit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnExit.setForeground(new java.awt.Color(255, 255, 255));
        BtnExit.setText("Exit");
        BtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnPrev, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnExit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelPuzzleImages, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnNext)
                            .addComponent(BtnPuzzleSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(BtnEasy))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnInter)))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelDifficulity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnHard, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnExpert, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(16, 16, 16))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelDifficulity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(BtnEasy)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(BtnInter))
                                    .addComponent(LabelNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(BtnHard))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BtnExpert)
                                    .addComponent(jLabel5))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnExit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnPrev))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelPuzzleImages, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtnPuzzleSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnNext)))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnEasyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEasyActionPerformed
        // TODO add your handling code here:
//        setImages(puzzlesEasy);
        chooseDiff(puzzlesEasy);
        choosePuzzles();
        LabelDifficulity.setText("Easy");
        BtnNext.setVisible(true);
        BtnPrev.setVisible(true);
        BtnPuzzleSelect.setVisible(true);

    }//GEN-LAST:event_BtnEasyActionPerformed

    private void BtnInterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInterActionPerformed
        // TODO add your handling code here:
//        setImages(puzzlesInter);
        chooseDiff(puzzlesInter);
        choosePuzzles();
        LabelDifficulity.setText("Inter");
        BtnNext.setVisible(true);
        BtnPrev.setVisible(true);
        BtnPuzzleSelect.setVisible(true);

    }//GEN-LAST:event_BtnInterActionPerformed

    private void BtnHardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHardActionPerformed
        // TODO add your handling code here:
//        setImages(puzzlesHard);
        chooseDiff(puzzlesHard);
        choosePuzzles();
        LabelDifficulity.setText("Hard");
        BtnNext.setVisible(true);
        BtnPrev.setVisible(true);
        BtnPuzzleSelect.setVisible(true);

    }//GEN-LAST:event_BtnHardActionPerformed

    private void BtnExpertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExpertActionPerformed
        // TODO add your handling code here:
//        setImages(puzzlesExpert);
        chooseDiff(puzzlesExpert);
        choosePuzzles();
        LabelDifficulity.setText("Expert");
        BtnNext.setVisible(true);
        BtnPrev.setVisible(true);
        BtnPuzzleSelect.setVisible(true);

    }//GEN-LAST:event_BtnExpertActionPerformed

    private void BtnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrevActionPerformed
        // TODO add your handling code here:
        choosePuzzles(BtnPrev);

    }//GEN-LAST:event_BtnPrevActionPerformed

    private void BtnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNextActionPerformed
        // TODO add your handling code here:
        choosePuzzles(BtnNext);

    }//GEN-LAST:event_BtnNextActionPerformed

    private void BtnPuzzleSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPuzzleSelectActionPerformed
        // TODO add your handling code here:
        String type = LabelDifficulity.getText();
        System.out.println(type);
        int puzzleNumber = count;
        System.out.println(puzzleNumber);

        String[] puzzle = {
            "--74916-5",
            "2---6-3-9",
            "-----7-1-",
            "-586----4",
            "--3----9-",
            "--62--187",
            "9-4-7---2",
            "67-83----",
            "81--45---"
        };

        String[] solution = {
            "387491625",
            "241568379",
            "569327418",
            "758619234",
            "123784596",
            "496253187",
            "934176852",
            "675832941",
            "812945763"
        };

        switch (type) {
            case "Easy" -> {
                System.out.println("Case Easy");
                puzzle = puzzlesAndSolutions.getPuzzleEasy()[puzzleNumber];
                solution = puzzlesAndSolutions.getSolutionEasy()[puzzleNumber];
            }
            case "Inter" -> {
                System.out.println("Case Inter");
                puzzle = puzzlesAndSolutions.getPuzzlesInter()[puzzleNumber];
                solution = puzzlesAndSolutions.getSolutionInter()[puzzleNumber];
            }
            case "Hard" -> {
                System.out.println("Case Hard");
                puzzle = puzzlesAndSolutions.getPuzzlesHard()[puzzleNumber];
                solution = puzzlesAndSolutions.getSolutionsHard()[puzzleNumber];
            }
            case "Expert" -> {
                System.out.println("Case Expert");
                puzzle = puzzlesAndSolutions.getPuzzlesExpert()[puzzleNumber];
                solution = puzzlesAndSolutions.getSolutionsExpert()[puzzleNumber];
            }
            default -> {
            }
        }

        Sudoku sudoku = new Sudoku(String.valueOf(puzzleNumber + 1), puzzle, solution);
        this.dispose();


    }//GEN-LAST:event_BtnPuzzleSelectActionPerformed

    private void BtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BtnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DifficultyChooserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DifficultyChooserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DifficultyChooserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DifficultyChooserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DifficultyChooserGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEasy;
    private javax.swing.JButton BtnExit;
    private javax.swing.JButton BtnExpert;
    private javax.swing.JButton BtnHard;
    private javax.swing.JButton BtnInter;
    private javax.swing.JButton BtnNext;
    private javax.swing.JButton BtnPrev;
    private javax.swing.JButton BtnPuzzleSelect;
    private javax.swing.JLabel LabelDifficulity;
    private javax.swing.JLabel LabelNum;
    private javax.swing.JLabel LabelPuzzleImages;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public void choosePuzzles(JButton z) {

        if (z == BtnPrev) {
            count--;
        } else {
            count++;
        }
        if (count >= currentPuzzles.length) {
            count = 0;
        } else if (count < 0) {
            count = currentPuzzles.length - 1;
        }

        LabelNum.setText("Puzzle #" + String.valueOf(count + 1));
        LabelPuzzleImages.setIcon(currentPuzzles[count]);
    }

    public void choosePuzzles() {
        count = 0;
        LabelNum.setText("Puzzle #" + String.valueOf(count + 1));
        LabelPuzzleImages.setIcon(currentPuzzles[count]);
    }

    public static BufferedImage resizeImage(BufferedImage originalImage, int width, int height) {
        Image tmp = originalImage.getScaledInstance(width, height, Image.SCALE_SMOOTH);
        BufferedImage resized = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);

        Graphics2D g2d = resized.createGraphics();
        g2d.drawImage(tmp, 0, 0, width, height, null);
        g2d.dispose();

        return resized;
    }

    public void chooseDiff(ImageIcon[] x) {
        currentPuzzles = x;
    }

    private void setImages(ImageIcon[] puzzle_images, String path) {
        int i = 0;
        for (String end : endPath) {
            File file = new File(path + end + ".png");
            try {
                BufferedImage image = ImageIO.read(file);
                BufferedImage resizedImage = resizeImage(image, 311, 311);
                ImageIcon image1 = new ImageIcon(resizedImage);
                puzzle_images[i] = image1;
                i++;
            } catch (Exception e) {
            }
        }

    }

}
